tasker_web/tasker/urls.py
from django.conf.urls import include, url
from . import views
import django.contrib.auth.views as auth_views
from django.views.generic import RedirectView

task_patterns = [
    url(r'^$', views.TaskListView.as_view(), name='all'),
    url(r'^add/', views.TaskCreateView.as_view(), name='add'),
    url(r'^history/', views.TaskHistoryVies.as_view(), name='history'),
    url(r'^(?P<pk>\d+)/$', views.TaskWorkView.as_view(), name='work'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_task_view, name='delete'),
    url(r'^(?P<pk>\d+)/complete/$', views.complete_task_view, name='complete'),
    url(r'^(?P<pk>\d+)/edit/$', views.TaskEditView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/add_user', views.add_user_from_task, name='add_user'),
    url(r'^(?P<pk>\d+)/delete_user/(?P<name_user>\w+)/$',
        views.delete_user_from_task, name='delete_user'),
    url(r'search/',
        views.search, name='search'),
    url(r'^(?P<pk>\d+)/revive/$', views.revive_the_task, name='revive'),
    url(r'^(?P<pk>\d+)/clear/$', views.clear_task, name='clear'),
    url(r'^(?P<pk>\d+)/add-subtask/$', views.CreateSubtaskView.as_view(), name='add-subtask')                                
]
plan_patterns = [
    url(r'^$', views.PlanTaskListView.as_view(), name='all_plantask'),
    url(r'^add/', views.PlanTaskCreateView.as_view(), name='add_plantask'),
    #correct to info 
    url(r'^(?P<pk>\d+)/$', views.PlanTaskWorkView.as_view(), name='work'),
    url(r'^(?P<pk>\d+)/edit/$', views.PlanTaskEditView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_plantask_view, name='delete'),
]
urlpatterns = [
    url(r'^$', RedirectView.as_view(url='tasks'), name='homepage'),
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.logout,
        {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^tasks/', include(task_patterns, namespace='tasks')),
    url(r'^plantask/', include(plan_patterns, namespace='plantask')),
]

tasker_web/tasker_web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('tasker.urls')),
    url(r'^admin/', admin.site.urls),
]

tasker_web/tasker/forms.py
from mytasker.models import( 
    Task,
    PlanTask
)
from django import forms
import datetime
from mytasker.constants import PRIORITIES


class DateTimeLocalInput(forms.DateTimeInput):
    def format_value(self, value):
        if isinstance(value, datetime.datetime):
            return str(value.strftime('%Y-%m-%d %H:%M'))
        return str(value)


class CreateTaskForm(forms.ModelForm):
    subtasks = forms.ModelChoiceField(label='Parent task',
                                      queryset=Task.objects.none(),
                                      required=False)
    time_end = forms.DateTimeField(required=False,
                                   widget=DateTimeLocalInput(attrs={'type': "datetime-local"}),
                                   input_formats=['%Y-%m-%dT%H:%M'])
    task_priority = forms.ChoiceField(choices=PRIORITIES)

    def __init__(self, tasks, *args, **kwargs):
        super(CreateTaskForm, self).__init__(*args, **kwargs)
        if tasks:
            self.fields['subtasks'].queryset = tasks

    class Meta:
        model = Task
        fields = ['task_name', 'task_info',
                  'time_end',  'tags', 'task_priority']

class PlanModelForm(forms.ModelForm):
    period = forms.IntegerField()
    deadline = forms.DateTimeField(required=False,
                                   widget=DateTimeLocalInput(attrs={'type': "datetime-local"}),
                                   input_formats=['%Y-%m-%dT%H:%M'])

    class Meta:
        model = PlanTask
        fields = ['task_name', 'info', 'deadline', 'period_type','period']

class TaskAddUserForm(forms.Form):
    user_to = forms.CharField(label='User Name',
                                widget=forms.TextInput(attrs={'placeholder': 'Input Name User'}))


class CreateSubtaskForm(forms.ModelForm):

    time_end = forms.DateTimeField(required=False,
                                   widget=DateTimeLocalInput(attrs={'type': "datetime-local"}),
                                   input_formats=['%Y-%m-%dT%H:%M'])
                                   
    def __init__(self, *args, **kwargs):
        self._parent_task = kwargs.pop('subtasks')
        super(CreateSubtaskForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = ['task_name', 'task_info',
                  'time_end',  'tags', 'task_priority']

tasker_web/tasker/views.py
from mytasker.models import (
    Task,
    PlanTask
)
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from mytasker.db_manage import Manage
from django.urls import reverse_lazy


db = Manage()


def signup(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


#####################################################


class TaskCreateView(LoginRequiredMixin, CreateView):
    form_class = CreateTaskForm
    template_name = 'master/add_task.html'
    model = Task

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        tasks = db.find_tasks(self.request.user.username, general=False)
        kwargs.update({'tasks': tasks})
        return kwargs

    def form_valid(self, form):
        username = self.request.user.username
        new_task = form.save(commit=False)
        new_task.owner = db.get_users(self.request.user.username)
        new_task.save()
        parent_task = form.cleaned_data['subtasks']
        parent_task.add_subtask(new_task) if parent_task else db.add_created(
            username, 'task', new_task)
        if parent_task:
            for owner in parent_task.other_user_task.all():
                add_user_from_task(self.request, new_task.pk, owner)
        return redirect('homepage')


class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'master/home_page.html'
    model = Task
    context_object_name = 'tasks'

    def get_queryset(self):
        username = self.request.user.username
        return db.find_tasks(username)


class TaskHistoryVies(LoginRequiredMixin, ListView):
    template_name = 'master/home_page.html'
    model = Task
    context_object_name = 'tasks'

    def get_queryset(self):
        username = self.request.user.username
        tasks = db.find_tasks(username, history=True, general=False)
        return tasks


class TaskWorkView(LoginRequiredMixin, DetailView):

    model = Task
    template_name = 'master/work_with_task.html'
    content_object_name = 'task'

    def get_object(self, queryset=None):
        task = db.find_tasks(
            username=self.request.user.username, task_id=self.kwargs['pk'])
        return task


class TaskEditView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'master/add_task.html'

    fields = ['task_name', 'task_info',
              'time_end',  'tags', 'task_priority', 'status']

    def get_success_url(self):
        return reverse_lazy('tasks:work', args=(self.object.pk,))


class CreateSubtaskView(CreateView):
    form_class = CreateSubtaskForm
    template_name = 'master/add_task.html'

    def get_form_kwargs(self):
        kwargs = super(CreateSubtaskView, self).get_form_kwargs()
        parent_task = db.find_tasks(self.request.user.username, self.kwargs['pk'])
        kwargs.update({'subtasks': parent_task})
        return kwargs

    def form_valid(self, form):
        username = self.request.user.username
        parent_task = db.find_tasks(username, self.kwargs['pk'])
        new_task = form.save(commit=False)
        new_task.owner = db.get_users(self.request.user.username)
        new_task.save()
        parent_task.add_subtask(new_task)
        return redirect('tasks:work', self.kwargs['pk'])


def delete_task_view(request, pk):
    username = request.user.username
    db.delete_task(username, pk)
    return redirect('homepage')


def complete_task_view(request, pk):
    username = request.user.username
    db.complete_task(username, pk)
    return redirect('homepage')


@login_required
def add_user_from_task(request, pk, user=None):
    
    form = TaskAddUserForm(request.POST or None)
    if user:
        username = db.get_users(username=request.user.username)
        task_to_share = db.find_tasks(username, pk)
        add(username, task_to_share, user)
    else:
        if request.method == 'POST':
            if form.is_valid():
                username = db.get_users(username=request.user.username)
                user_to = db.user_to_add_task(username=form.cleaned_data['user_to'])
                if user_to is not None:
                    task_to_share = db.find_tasks(username, pk)
                    add(username, task_to_share, user_to)
                    return redirect('tasks:work', pk)
                else:
                    form = TaskAddUserForm( None)
                    form.fields['user_to'].widget.attrs['placeholder'] = 'Incorrect input name'
                
        return render(request, 'master/add_user_from_task.html', {'form': form})


def add(username, task_to_share, user_to):
    user_to.add_task_from_user(task_to_share)
    if task_to_share.sub.all().exists():
        for subtask in task_to_share.sub.all():
            add(username, subtask, user_to)


@login_required
def delete_user_from_task(request, pk, name_user):
    username = request.user.username
    db.delete_user_from_task(username, pk, name_user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def search(request):
    username = request.user.username
    if request.method == "GET":
        name_task = request.GET['task_search']
        tasks = db.find_tasks(username, tags=name_task, general=False)
        return render(request, 'master/home_page.html', {'tasks': tasks})


@login_required
def revive_the_task(request, pk):
    username = request.user.username
    db.revive_task(username, pk)
    return redirect('tasks:history')


def clear_task(request, pk):
    username = request.user.username
    db.db_remove_task(username, pk)
    return redirect('tasks:history')


###########################################################


class PlanTaskCreateView(LoginRequiredMixin, CreateView):
    model = PlanTask
    form_class = PlanModelForm
    template_name = 'master/add_task.html'

    def form_valid(self, form):
        username = self.request.user.username
        new_plan = form.save(commit=False)
        new_plan.save()
        db.add_created(username, 'plan', new_plan)
        return redirect('homepage')


class PlanTaskWorkView(LoginRequiredMixin, DetailView):

    model = PlanTask
    template_name = 'master/work_with_task.html'
    content_object_name = 'plantask'

    def get_object(self, queryset=None):
        plantask = db.find_plantask(
            username=self.request.user.username, plan_id=self.kwargs['pk'])
        return plantask


class PlanTaskEditView(LoginRequiredMixin, UpdateView):
    model = PlanTask
    form_class = PlanModelForm
    template_name = 'master/add_task.html'
   
    def get_success_url(self):
        return reverse_lazy('plantask:all_plantask')


class PlanTaskListView(LoginRequiredMixin, ListView):
    template_name = 'master/home_page.html'
    model = PlanTask
    context_object_name = 'plans'

    def get_queryset(self):
        username = self.request.user.username
        return db.find_plantask(username)


def delete_plantask_view(request, pk):
    username = request.user.username
    db.delete_plantask(username, pk)
    return redirect('plantask:all_plantask')

tasker_web/tasker/templates/master/add_task.html
{% extends 'master/base.html' %} {% block content %}
<div class="form-wrapper">
    {% if 'add' in request.path %}
    <h4 style="text-align: center; color: orange;">New Task</h4>
    {% endif %} 
    {% if error_message %}
        <p>
            <strong>{{ error_message }}</strong>
        </p>
    {% endif %}
    {% if 'edit' not in request.path and 'add-subtask' not in request.path%}
    <div style="text-align:center">
        
        <a href="{% url 'tasks:add'%}" style="width: 45%"  class="btn btn-danger">Task</a>
   
        <a href="{% url 'plantask:add_plantask'%}" style="width: 45%" class="btn btn-info">Plan</a>

    </div>
    {% endif %}
    <form role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {% include 'master/custom_form.html' %}
        <button type="submit" class="btn btn-success button">
            {% if 'add' in request.path %}Add 
            {% else %} Edit 
            {% endif %}
        </button>
    </form>
</div>
{% endblock %}

tasker_web/tasker/templates/master/add_user_from_task.html
{% extends 'master/base.html' %} 
{% block content %}

    <div class="form-wrapper" style="background: linear-gradient(to top, rgb(199, 193, 168) 20%, rgb(75, 133, 187) 50%, #A19887 80%);">
        <h4 style="text-align:center">Add task with</h4>
        <form role="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %} 
            {% include 'master/custom_form.html' %}
            <div class="form-group">
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-success button" 
                            style="text-align: senter;">Add User</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

tasker_web/tasker/templates/master/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tasker</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css" />
</head>


<body>
    {% include "master/header.html" %} {% block content %} {% endblock %}
</body>

</html>

tasker_web/tasker/templates/master/custom_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="container center" style="background-color: rgb(63, 117, 117);">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback" style="background-color: red;">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small style="color: rgb(218, 88, 29);" class="form-text">{{ field.help_text|striptags }}</small>
        {% endif %}
    </div>
{% endfor %}

tasker_web/tasker/templates/master/header.html
<nav class="navbar navbar-inverse">

    <div class="collapse navbar-collapse">

        <a class="navbar-brand" href="{% url 'homepage' %}" 
            style="font-family: 'BioRhyme Expanded', serif;">MyTasker
        </a>

        {% if request.path != 'login' and request.path != 'signup' %}

        <a class="navbar-brand" href="{% url 'tasks:add' %}" 
            style="font-family: 'BioRhyme Expanded', serif;">Add
        </a>

        <a class="navbar-brand" href="{% url 'plantask:all_plantask' %}" 
            style="font-family: 'BioRhyme Expanded', serif;">Plans
        </a>
        <a class="navbar-brand" href="{% url 'tasks:history' %}" 
            style="font-family: 'BioRhyme Expanded', serif;">History
        </a>

        <form method="GET" class="navbar-form navbar-left" action="{% url 'tasks:search' %}" role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Name Task or tag" 
                        name="task_search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="a navbar-right">
            <li class="a-item" style="background-color: transparent; text-align: center;">
                <button class="btn btn-danger text-center;" 
                    style=" text-align: center; margin:7px; opacity: 1;" type="button" 
                    data-toggle="dropdown">
                    {{ request.user.username }}
                </button>
                <ul class="suba">
                    <li class="suba-item" style="text-align: center;margin:7px; opacity: 1;">
                        <a href="{% url 'logout' %}" class="nav-link text-center" 
                            style="color: rgb(86, 143, 145);">Logout</a>
                    </li>
                </ul>
            </li>
        </ul>
        {% endif %}
    </div>
    </div>
</nav>

tasker_web/tasker/templates/master/home_page.html
{% extends 'master/base.html' %} 
{% load humanize %} 
{% block content %}
<div class="d-flex flex-wrap card-group">
    {% if 'plantask' not in request.path %} 
    {% for task in tasks %}

    <a href="{% url 'tasks:work' task.pk %}" style="text-decoration: none;">
        <div class="flex-fill p-2">
            <div class="show_task" style="background: linear-gradient(45deg, rgba(103, 0, 31, .8), rgba(34, 101, 163, .5)); margin-left: 150px;">
                {{ task.pk }}.
                Name: {{ task.task_name}}
                <hr>
                <div class="info_task">
                    Info: {{task.task_info}}
                </div>
                <div style="vertical-align:bottom;">
                    {{task.time_end}}
                </div>
                <div style="vertical-align:bottom;
                    {% if task.task_priority == 1 %} color: chartreuse
                    {% elif task.task_priority == 2%} color: yellow
                    {% elif task.task_priority == 3%} color: #FF7F50
                    {% else %} color: rgb(228, 36, 29)
                    {% endif%}
                ">
                    Priority: 
                    {% if task.task_priority == 1 %} Low
                    {% elif task.task_priority == 2%} Average
                    {% elif task.task_priority == 3 %} High 
                    {% else %} Ultrahigh
                    {% endif%}
                </div>
                <div style="vertical-align:bottom;">
                    Tags: {{task.tags}}
                </div>
            </div>
        </div>
    </a>
    {% empty %} 
        {% if 'search' in request.path %}
            <h1 style="text-align: center; color: darkkhaki" class="display-3">
                No such tasks were found
            </h1>
        {% else %}
            <h1 style="text-align: center; color: darkkhaki">
                You do not have any tasks yet
            </h1>
        {% endif %}
    {% endfor %} 
    {% else %} 
    {% for plan in plans %}
    <a style="text-decoration: none;" href="{% url 'plantask:work' plan.pk %}">
        <div class="flex-fill p-2">
            <div class="show_task" style="background: linear-gradient(45deg, rgba(103, 0, 31, .8), rgba(34, 101, 163, .5)); margin-left: 150px;">
                Name: {{ plan.task_name}}
                <hr>
                <div class="info_task">
                    Info: {{plan.info}}
                </div>
                <div class="info_task">Repeat: Every {{plan.period}} 
                    {% if plan.period_type == 1 %} Hour
                    {% elif plan.period_type == 2 %} Day
                    {% elif plan.period_type == 3 %} Week  
                    {% elif plan.period_type == 4 %} Month
                    {% else %} Year {% endif%} 
                </div>
            </div>
        </div>
    </a>
    {% empty %} 
        <h1 style="text-align: center; color: darkkhaki">
            You do not have any plantasks yet
        </h1>
    {% endfor %} {% endif %}
</div>
{% endblock %}

tasker_web/tasker/templates/master/work_with_task.html
{% extends 'master/base.html' %} {% load humanize %} {% block content %}
<div class="form-wrapper" style="background: linear-gradient(to top, #E4AF9D 20%, #E4E4D8 50%, #A19887 80%);">
    {% if 'plantask' not in request.path %}
    <h3 class="text-center"> Name:
        <b>{{ task.task_name }}</b>
    </h3>
    <div>
        <label for="label_task_info" class="col-sm-5 control-label" style="color: black">Info:</label>
        <div style="text-align: center; margin: 5px;" id="label_task_info"> {{task.task_info}}</div>
        <label for="label_task_deadline" class="col-sm-5 control-label" style="color: black">Deadline:</label>
        <div style="text-align: center; margin: 5px;" id="label_task_deadline"> {{task.time_end|default:"No deadline" }}</div>
        <label for="label_task_priority" class="col-sm-5 control-label" style="color: black">Priority:</label>

        <div style="text-align: center; margin: 5px;" id="label_task_priority">
            {% if task.task_priority == 1 %} Low 
            {% elif task.task_priority == 2 %} Average 
            {% elif task.task_priority == 3 %} High 
            {% else %} Ultrahigh
            {% endif%}
        </div>
        <label for="label_task_tag" class="col-sm-5 control-label" style="color: black">Tag</label>
        <div style="text-align: center; margin: 5px;" id="label_task_status">{{task.tags}}</div>
        <label for="label_task_status" class="col-sm-5 control-label" style="color: black">Status:</label>
        <div style="text-align: center; margin: 5px;" id="label_task_status">{{task.status}}</div>
        {% if task.status != 'Complete' and task.status != 'Remove'%} {% if task.sub.all.exists %}

        <ul class="topmenu">

            <li>
                <a href="" class="submenu-link">Subtasks:</a>
                <ul class="submenu">
                    {% for sub in task.sub.all %} {% if sub.status != 'Remove' %}
                    <li>
                        <a href="{% url 'tasks:work' sub.pk %}">{{sub.task_name}}</a>
                    </li>
                    {% endif %} 
                    {% endfor %}
                </ul>
            </li>

        </ul>
        {% endif %} {% if task.other_user_task.all.exists %} {% if task.owner.name == request.user.username %}
        <ul class="topmenu">
            <li>
                <a href="" class="submenu-link">Users:</a>
                <ul class="submenu">
                    {% for owner in task.other_user_task.all %}
                    <li>
                        <div style="background-color: transparent; text-align: left; width: 1px;">

                            <button class=" button_delete_user btn btn-default">{{ owner }}
                                <a href="{% url 'tasks:delete_user'  pk=task.pk name_user=task.other_user_task.all.first %}" class="btn bg-danger btn-sm">
                                    <i class="fas fa-trash white" style="color: black; width: 10px; "></i>
                                </a>

                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
        {% endif %} {% endif %} 
        {% if task.status != 'Remove' and task.status != 'Complete'%}
            <div style="text-align: center; ">

                <a href="{% url 'tasks:edit' task.pk %}" class="btn btn-warning main_link" ">
                    <i class="fas fa-edit"></i>
                    Edit  </a>

                <a href="{% url 'tasks:delete' task.pk %}" class="btn btn-danger main_link">
                    <i class="fas fa-trash-alt"></i>
                    Delete</a>

                <br>
                <a href="{% url 'tasks:complete' task.pk %}" class="btn btn-success main_link">
                    <i class="far fa-calendar-check"></i>
                    Complete</a>

                {% if task.owner.name == request.user.username %}
                    <a href="{% url 'tasks:add_user' task.pk %}" class="btn btn-info main_link">
                        <i class="fas fa-user-plus"></i>
                        Add user</a>
                {% endif %} 
                <br>
                <a href="{% url 'tasks:add-subtask' task.pk %}" 
                    class="btn bg-info main_link">
                    <i class="fas fa-plus-circle"></i>
                    Add Subtask
                </a>
        {% endif %}
        </div>
        {% else %}
        <div style="text-align:center;">
        <a href="{% url 'tasks:revive' task.pk %}" class="btn btn-warning ">
            <i class="fab fa-firstdraft"></i>
            Revive task</a>
        <a href="{% url 'tasks:clear' task.pk %}" class="btn btn-danger ">
                <i class="fas fa-eraser"></i>
                Clear</a>
        </div>
        {% endif %}
    </div>
{% else %}
    <h3 class="text-center"> Name:
        <b>{{ plantask.task_name }}</b>
    </h3>
        <div class="info_task">
            Info: {{plantask.info}}
        </div>
        <div class="info_task">Repeat: Every {{plantask.period}} 
            {% if plantask.period_type == 1 %} Hour
            {% elif plantask.period_type == 2 %} Day
            {% elif plantask.period_type == 3 %} Week  
            {% elif plantask.period_type == 4 %} Month
            {% else %} Year {% endif%} 
        </div>
        <div style="text-align: center; ">
            <a href="{% url 'plantask:edit' plantask.pk %}" class="btn btn-warning main_link">
                <i class="fas fa-edit"></i>
                Edit</a>
            <a href="{% url 'plantask:delete' plantask.pk %}" class="btn btn-danger main_link">
                <i class="fas fa-trash-alt"></i>
                Delete</a>
            <br>
        </div>
{% endif %}
</div>


{% endblock %}